# Generated by Django 4.2.5 on 2023-09-26 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime_forum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='anime',
        ),
    ]
