# Generated by Django 4.2.5 on 2023-09-15 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_forum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddAnime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime_name', models.CharField(max_length=100)),
                ('anime_image', models.ImageField(upload_to='images/anime')),
                ('anime_description', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/users'),
        ),
    ]
