# Generated by Django 4.2.5 on 2023-09-28 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_forum', '0002_remove_comment_anime'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comments_count',
            field=models.ManyToManyField(blank=True, related_name='comment_count', to='anime_forum.post'),
        ),
    ]
