# Generated by Django 4.2.5 on 2023-09-28 04:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anime_forum', '0003_comment_comments_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comments_count',
            field=models.ManyToManyField(blank=True, related_name='comment_count', to=settings.AUTH_USER_MODEL),
        ),
    ]
