# Generated by Django 4.2.5 on 2023-09-28 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime_forum', '0004_alter_comment_comments_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comments_count',
        ),
    ]
