# Generated by Django 4.2.5 on 2023-10-03 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_forum', '0008_alter_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='replys',
            name='reply_count',
            field=models.ManyToManyField(blank=True, related_name='reply_count', to='anime_forum.comment'),
        ),
    ]
